region: us-east-2
licenseFilePath: test-license.key
route53Zone: pulumi-ce.team
route53Subdomain: mitchselftest
# dockerHubUsername: pulumibot
# dockerHubAccessToken: "]x4p>cR^C^DbEeEnukG@"
# imageTag: 20211227-174-signed
# imageTag: 20211209-134-signed # image Phil tested with
# imageTag: 20211123-89-signed # pre hide email option image
imageTag: latest

# Optional SAML SSO option
samlSsoEnabled: false

# Optional hide email settings
consoleHideEmailSignup: false # false = makes email signup available on console; true = hides email sign up option on console  
consoleHideEmailLogin: false  # false = allows email login on console; true = hides email login on console   
apiDisableEmailSignup: false # false = service api allows email signup; true = service api disallows email signup.  
apiDisableEmailLogin: false # false = service api allows email login; true = service api disabllows email signup.   

# Optional SMTP Settings
# smtpServer: smtp.example.com:587
# smtpUsername: johndoe
# smtpPassword: abcdefghi
# smtpGenericSender: sender@domain.com

# overrides for 01-cluster-configuration
clusterConfig:
  stackName: mitch-pulumi-selfhosted-01-cluster-configuration
  clusterVersion:
    value: "1.22" 
    # value: "1.18" 

# overrides for 02-cluster-services
clusterServicesConfig:
  stackName: mitch-pulumi-selfhosted-02-cluster-services
  dbReplicas:
    value: 1
  dbInstanceType:
    value: db.t3.medium

# overrides for 03-apps
appsConfig:
  stackName: mitch-pulumi-selfhosted-03-apps
  apiReplicas:
    value: 1
  consoleReplicas:
    value: 1
